docs/source/about-introduction.md, workflow/Snakefile, workflow/config/config.osw.yaml, workflow/config/config.yaml, workflow/scripts/add_electricity.py, workflow/scripts/build_bus_regions.py, workflow/scripts/build_load_data.py, workflow/scripts/generate_stochastic_samples.py, workflow/scripts/modify_network_osw.py, workflow/scripts/simplify_network.py, workflow/scripts/solve_operations_model.py
Included in this PR:
- Operations-only optimization branch of snakemake 
- Offshore Wind Transmission Study updates. Enabled in separate config
- Small documentation updates
=> Operations Model Branch PR

workflow/config/config.osw.yaml, workflow/config/config.yaml, workflow/envs/environment.yaml, workflow/scripts/_helpers.py, workflow/scripts/build_base_network.py, workflow/scripts/build_bus_regions.py, workflow/scripts/build_renewable_profiles.py, workflow/scripts/cluster_network_eur.py, workflow/scripts/simplify_network.py
=> Updating Versioning

workflow/rules/build_sector.smk, workflow/scripts/build_clustered_population_layouts.py
Closes #75 
In this PR I added logic to cluster populations, based on the PyPSA-Eur implementation with minor changes.
=> Add `build_clustered_population_layouts`

workflow/rules/build_sector.smk
In this PR I add the rule `build_simplified_population_layouts` based on the PyPSA-Eur implementation
=> simplified population layouts

workflow/config/config.default.yaml, workflow/rules/build_sector.smk, workflow/scripts/build_cop_profiles.py
In this PR I have added logic to calculated coefficient of performance profiles based on the PyPSA-Eur implementation
=> Added `build_cop_profiles`

workflow/Snakefile, workflow/config/config.default.yaml, workflow/envs/environment.yaml, workflow/scripts/build_renewable_profiles.py, workflow/scripts/retrieve_databundles.py
Closes:
Pins Dependencies so we don't keep running into issues.
=> 100 sandbox zenodo repo deleted

workflow/Snakefile, workflow/config/config.default.yaml, workflow/envs/environment.yaml, workflow/scripts/add_electricity.py, workflow/scripts/build_renewable_profiles.py
Closes #110, and bug with wind profiles not calculating
-NA
=> 110 duplicated renewable plants

workflow/scripts/retrieve_eia_data.py
Closes #112 
Switch columns from EIA930 to use the EIA corrected demand data. Fixes issue of negative demand from BANC.
=> fix incorrect demand data

workflow/envs/environment.yaml
Add plotly dependency to environment file
=> Add `plotly` dependency

workflow/config/config.api.yaml, workflow/scripts/eia.py
In this PR I implement logic to extract data from the [EIA API](https://www.eia.gov/opendata/browser/). My thoughts are we are starting to have a bunch of different data come from the EIA, and standardizing this would be useful. 
@ktehranchi your thoughts on this would be great!! :) 
- See module header for example
- The code shows how I envision the implementation (but am very open to other implementations!) 
- Extraction of fuel costs by fuel (gas and coal) and industry is implemented 
- Gas imports and exports by point of entry is implemented 
- Proposed code is extensible to add new API calls for specific data. The user really just needs to add the API call and raw data formatting logic. 
- Control of output data formats. Using the API, it is much easier to standarize dataframe …
=> Extraction of EIA Data

docs/source/config-configuration.md, docs/source/configtables/sector.csv, docs/source/rules-solve.md, workflow/config/config.default.yaml
Closes #164 
Changes include: 
- Fixing sector datatable 
- Fixing `config.default.yaml` docs parsing 
- Fixing solve and prepare network rule module references
=> Fix documentation building 

docs/source/rules-retrieving-data.md
Closes #193 
Add documentation for the retrieval of EFS data
=> Add EFS documentation 

workflow/scripts/add_electricity.py, workflow/scripts/build_renewable_profiles.py
Closes #184
In this PR I have updated the snapshot filtering for reading in efs data
=> Fixes bug in reading efs data

workflow/rules/build_electricity.smk, workflow/scripts/add_electricity.py, workflow/scripts/build_demand.py
Closes #188 #184 
- Separates demand cleaning and transforming from add_electricity and moved into new module named `build_demand`
- Fixes bug related to #184 : Now all snapshots will be aligned to that in the config file.... i.e. no more timeshifting to reconcile the timezone changes. All times are in UTC.
=> New module for build_demand

workflow/rules/validate.smk, workflow/scripts/plot_validation_production.py
I forgot to update save paths for validation plots in PR #155. This PR addresses that
=> Fix Save Paths in Validation Module 

.gitignore, workflow/rules/build_electricity.smk, workflow/scripts/add_electricity.py, workflow/scripts/build_fuel_prices.py, workflow/scripts/eia.py
Closes #206 
In this PR I have updated the logic to pull in historical gas and coal costs
=> Update dynamic pricing 

workflow/scripts/regional_dashboard.py
In this PR I add an example dashboard for viewing results. This is just an example of how we could implement an interactive method to interrogate the model. Def a little buggy still, but just meant to be a proof of concept :)
=> Example Dashboard 

workflow/scripts/build_fuel_prices.py, workflow/scripts/eia.py, workflow/scripts/retrieve_eia_data.py
Closes #250 
In this PR I fix the extraction of coal costs from the EIA. I have: 
- Changed API call to get receipt price data
- This change fixed the issue of improper API behaviour, described in the issue ticket
- Update the return column headers of CoalCosts to match other data structures
=> Fix extraction of USA coal prices 

workflow/rules/retrieve.smk
Patch to fix filepath issue in PR #260 in `retrieve_caiso_data` rule
=> Fix caiso filepath in retrieve rule 

docs/source/about-install.md
Update install instructions to should how to clone via HTTPS. I don't believe GitHub recommends SSH over HTTPS (or visa versa), so showing both methods is added.
=> Update install instructions

.gitmodules, docs/source/about-install.md, workflow/rules/build_electricity.smk, workflow/rules/postprocess.smk, workflow/scripts/_helpers.py, workflow/scripts/copy_config.py, workflow/scripts/prepare_network.py
- Remove PyPSA-EUR as a submodule in the workflow (copy_config, prepare_network)
=> Removes PyPSA-Eur as a Submodule

workflow/rules/build_electricity.smk, workflow/rules/retrieve.smk, workflow/scripts/build_demand.py, workflow/scripts/constants.py, workflow/scripts/plot_loads.py
Closes #296 
In this PR I have added a dissagregation strategy for industrial loads. It is based on the [United States County-Level Industrial Energy Use](https://data.nrel.gov/submissions/97) dataset. All industrial load is treated equally here (ie. heat and electrical industry demand follow the same dissagregation logic). So for only state level dissagregation is supported (ie. EFS data works). 
**Note**: I think something is still off with the actual dissagreagtion. If I plot county level energy use, counties just north of LA have the highest energy use. However, if I plot clustered industrial load (based on EFS),  it shows the SF area as being the highest energy use. 
Im gonna move on to implementing the reading of the Industrial load dataset to see if I can find the issue while …
=> Add `WriteIndustrial` class

workflow/rules/build_electricity.smk, workflow/rules/retrieve.smk
Closes #305 
Fixed retrieval of sector databundles by adding in industrial load data.
=> Fix Zenodo Sector Databundle 

.github/ISSUE_TEMPLATE/bug_report.yaml
In this PR I have updated the bug issue template to require specifying a branch
=> update issue template

workflow/envs/environment.yaml, workflow/scripts/build_cost_data.py, workflow/scripts/retrieve_cost_data_eur.py, workflow/scripts/solve_network.py
Fix costs retrieval if a historical planning year is used. Code adapted from @ktehranchi's suggestion. Also remove a pdb import to fix pre-commit issues.
=> Fix costs year

workflow/rules/build_electricity.smk, workflow/rules/retrieve.smk, workflow/scripts/add_electricity.py, workflow/scripts/build_fuel_prices.py, workflow/scripts/build_powerplants.py, workflow/scripts/plot_statistics.py, workflow/scripts/plot_validation_production.py, workflow/scripts/retrieve_databundles.py
Closes #363 
In this PR I add logic to retrieve and use any EFS study. Users can select the EFS case (`reference`, `medium`, `high`) and speed (`slow`, `moderate`, `rapid`) from the config file.
=> Allow any EFS scenario

workflow/scripts/add_electricity.py, workflow/scripts/add_extra_components.py, workflow/scripts/prepare_network.py, workflow/scripts/summary.py
Closes #197 
- #197: Fixes long-standing error in plots when resampling or TSAM Aggregation is used. 
- Fixes a new bug i found on temporal resampling in multihorizon problems.
=> Fixes #197, Resampling Opt Bug

workflow/repo_data/config/config.plotting.yaml, workflow/scripts/add_extra_components.py
- Small bug on definition of additional technologies to add
=> Bug Fix for extra carrier addition

workflow/Snakefile, workflow/rules/common.smk, workflow/scripts/build_cost_data.py, workflow/scripts/cluster_network.py, workflow/scripts/constants.py, workflow/scripts/plot_network_maps.py, workflow/scripts/plot_statistics.py, workflow/scripts/plot_validation_production.py, workflow/scripts/prepare_network.py
1. Fixes issues in transport model mode where lines all ITLS were not correctly added to the network, and in the Texas interconnect case there would be a sub-network for the panhandle unnecessarily.
2. Updates Transmission Expansion Costs with TEPCC data
=> Fixes Transport Model Subnetwork Issues

workflow/Snakefile, workflow/rules/build_electricity.smk, workflow/rules/postprocess.smk, workflow/scripts/add_extra_components.py, workflow/scripts/build_renewable_profiles.py, workflow/scripts/cluster_network.py, workflow/scripts/constants.py, workflow/scripts/plot_network_maps.py, workflow/scripts/plot_statistics.py, workflow/scripts/solve_network.py
- Implements transmission expansion costs for zonal model from ReEDS Expansion data
- #380 Fixes perfect foresight land-use constraint
- Implements Max annual growth rate. Adds this config to `costs:`
```
costs:
max_growth:
base: # for new technology you can specify the first base value which growth rate factor is relative to. If not specified takes existing initial capacity.
SMR: 1000
rate: # Annual growth rate
SMR: 1.1
nuclear: 1.1
```
=> Fix Land-use Constraints, Implements Max Annual Growth Rate 

workflow/rules/common.smk, workflow/rules/solve_electricity.smk, workflow/scripts/cluster_network.py, workflow/scripts/prepare_network.py
- Changes transmission expansion for zonal model to have equal bi-directional expansion
- Updates cpu and memory request for solve_network in cluster configurations
=> Update Cluster Resource Request + Zonal Model Implementation

workflow/rules/build_electricity.smk
Closes #409 
In this PR I nest all intermediate demand files in a sub-directory. I also fix a bug where commercial demand was using residential demand files.
=> Fix com demand use

workflow/repo_data/config/config.common.yaml, workflow/scripts/cluster_network.py
=> Closes #421 - Patch for Highs

docs/source/data-industrial.md, docs/source/data-transportation.md, workflow/repo_data/config/config.default.yaml
Minor change to sector docs and removal of sector config from default config. This config is now in a seperate `config.sector.yaml` file.
=> Sector Docs Patch

.pre-commit-config.yaml
Same as PR #476, except target is master branch
=> Remove broken pre-commit rule (`docformatter`)

workflow/scripts/build_natural_gas.py
In this PR I update the natural gas filtering to match updated introduced in PR #453. This update removes the need for specific `gas trade` buses for states withing the geographic scope.
=> Correct domestic gas trade filtering

workflow/rules/build_electricity.smk, workflow/scripts/add_demand.py, workflow/scripts/build_demand.py
Closes #456,
Closes #484  
In this PR I update the EULP data to account for timezones. Also, all sector demand files are saved as pickle files to speed up adding demand to the network.
=> Updates to Sector Demand

workflow/repo_data/config/config.plotting.yaml
quick fix hydrogen naming bug in plotting config
=> config hydrogen hot fix

workflow/scripts/add_electricity.py, workflow/scripts/add_extra_components.py, workflow/scripts/plot_statistics.py
- Fixes bug where certain renewable generators had a build_year of zero.
- Refactored some of add_multihorizon_generators
- Plot updates
=> lifetime bug fix, plot updates

workflow/rules/build_electricity.smk, workflow/rules/postprocess.smk, workflow/scripts/add_extra_components.py, workflow/scripts/cluster_network.py, workflow/scripts/plot_statistics.py, workflow/scripts/prepare_network.py, workflow/scripts/scenario_comparison.py
- Fix reference point calculation for Line Limit (ll) for (vX) transmission expansion constraints in reeds network transport model.
- When modeling certain regions with ReEDS county resolution, we need to reconcile differences in the TAMU, and ReEDS networks. These edge-case inconsistencies caused an error to be thrown when modeling texas with county resolution.
- Bug with new carrier specification.
=> multiple fixes

workflow/repo_data/config/config.sector.yaml, workflow/scripts/build_electricity_sector.py, workflow/scripts/build_heat.py
Closes #508 
In this PR I update demand response cost accounting in sector studies. Specifically, different marginal costs can be applied to each carrier.
=> Different costs of sector demand response 

docs/source/config-sectors.md, docs/source/configtables/sector_industrial.csv, docs/source/configtables/sector_service.csv, docs/source/data-sectors.md, workflow/scripts/build_electricity_sector.py, workflow/scripts/build_heat.py, workflow/scripts/solve_network.py
Closes #511 
Allows sector demand respose to be applied at a per-carrier level.
=> Demand Response by Sector 

workflow/scripts/solve_network.py
Hotfix to allow `inf` as a restriction on shiftable load
=> Sector Demand Response Hotfix

.pre-commit-config.yaml, pyproject.toml
As part of clean-up I am switching to astrals ruff for linting.
=> Updates to pyproj and pre-commit

.pre-commit-config.yaml, pyproject.toml
Switching linting to astral's ruff for pre-commit, and removing duplicate pre-commits.
=> new linting

docs/source/about-install.md, docs/source/about-usage.md, pyproject.toml, uv.lock, workflow/scripts/add_electricity.py
Closes #483 
- Updates pyproject file to support UV for package management. 
- Updates docs with installation and usage instructions for UV
=> Migrate to UV for package management

README.md, workflow/scripts/build_cop_profiles.py, workflow/scripts/build_demand.py, workflow/scripts/build_natural_gas.py, workflow/scripts/build_sector_costs.py, workflow/scripts/build_stock_data.py, workflow/scripts/constants.py, workflow/scripts/constants_sector.py, workflow/scripts/eia.py, workflow/scripts/eulp.py, workflow/scripts/plot_natural_gas.py, workflow/scripts/plot_statistics_sector.py, workflow/scripts/plot_validation_sector.py, workflow/scripts/retrieve_eulp.py, workflow/scripts/summary_sector.py
Builds on PR #533 and #534 to update formatting for all sector coupling logic to follow Ruff guidelines. Also add in the Ruff and UV badges.
=> Ruff linting for sector specific scripts

workflow/Snakefile
Appends PR #538 where the sankey diagrams file extension changed. Forgot to push the snakefile in that PR.
=> Fix sankey file extension

workflow/scripts/build_sector_costs.py
Corrects small bug that was introduced while converting sector files to be ruff compliant in PR #537
=> Sector costs hotfix

workflow/scripts/plot_statistics_sector.py
Minor corrections to sector plots for situations where no data exists.
=> Sector plots update

workflow/scripts/add_electricity.py
Modify battery efficiencies to align with NREL ATB
=> Modify battery efficiencies to align with NREL ATB (issue-527)

workflow/scripts/solve_network.py
Closes #522 
In this PR I have:
- Updated the TCT constraint to work with Links
- Corrected the CO2L sector constraint to be applied at every time slice, rather than just the last one
- Simplified the CO2L sector constraints
=> Update Sector CO2L and TCT Constraints

workflow/scripts/solve_network.py
Closes #580 
Restores the conditional in solve network that was removed in PR #576
=> Restores conditional for foresight option in sovle network 

workflow/scripts/solve_network.py
Closes #574 
Fixes the RPS constraint when running sector studies. Instead of comparing the RPS against the exogenous electrical load, its compared against the endogenous out flowing power sector energy. 
Need to test a couple more edge cases, but should be good to merge.
=> Add sector RPS constraint

workflow/scripts/build_base_network.py, workflow/scripts/build_demand.py
=> Fix EIA demand scaler bug, Missing SD zone

workflow/rules/build_electricity.smk, workflow/run_slurm.sh, workflow/scripts/solve_network.py
Quick lil fix for bug I introduced on import structure in #603
=> bug fix: solve imports issue from testing

workflow/scripts/build_heat.py, workflow/scripts/build_sector_costs.py
Correct two costs errors with the service section end-use capital costs.
=> Sector cost corrections

workflow/repo_data/ReEDS_Constraints/transmission/README.md, workflow/scripts/build_co2_storage.py, workflow/scripts/test/README.md
Corrects issues with precommit from `v0.7.0`
=> Precommit Fixes for `v0.7.0`

workflow/repo_data/config/config.default.yaml, workflow/scripts/build_renewable_profiles.py, workflow/scripts/zenodo_downloader.py
- added configs for renewable data set selection in default config file
- [check ] I tested my contribution locally and it seems to work fine.
=> (Updated) adding renewable configs to config.default.yaml

workflow/scripts/zenodo_downloader.py
Updates for Ruff in `zenodo_downloader` so `pre-commit` passes
=> Fix Ruff precommit issues in Zenodo Downloader 
