- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/docs.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- .github/pull_request_template.md
In this PR I have added: 
- A pull request template
- A Bug Report issue template 
- A Feature Request issue template 
- A Documentation issue template 
These templates are based off of the PyPSA-Eur ones. However, the issue templates have been updated to be `*.yaml` files to allow web form fields.
> Issue templates

- workflow/Snakefile
- workflow/scripts/build_renewable_profiles.py
- workflow/scripts/retrieve_cost_data_usa.py
Closes #95 (Temp fix)
In this PR I comment out the extraction of transportation costs, as it was throwing an error and is not currently used. Issue #97 addresses this. 
I also fixed the `mock_snakemake()` call in `build_renewable_profiles` to accept the `interconnect` wildcard
> Comment Transporation Costs

- workflow/scripts/build_renewable_profiles.py
reverts change made in #187 that changed the snapshots overwhich build_renewable_profiles was run. Previous implementation would try to build profiles outside the period which the cutout had data for.
> revert brp to retain snapshots in config file

- .gitignore
- workflow/config/config.api.yaml
Fixes the `config.api.yaml` file not being tracked by the `.gitignore`. For reference, I followed the suggestion in [this stack overflow thread](https://stackoverflow.com/a/64206592) to fix the issue! :)
> Fixes `config.api.yaml` not being tracked by `.gitignore`

- workflow/scripts/plot_statistics.py
- workflow/scripts/summary.py
In this PR I have switched emissions accounting to use the `pypsa.statistics.StatisticsAccessor` methods. Specifically I have: 
1. Added a new function to find primary energy consumption called `get_primary_energy_use`
2. Added a new function to find generator/node/carrier emissions called `get_node_carrier_emissions_timeseries`
3. Modified the `get_node_emissions_timeseries` and `get_technology_emissions_timeseries` functions to use the `get_node_carrier_emissions_timeseries`
While two new functions are added, overall, the logic is much simpler as we are not looping over all the different components to find primary energy use. 
I did a qualitative check on the graphs to make sure the results have not changed.
> Switch Emission Accounting to PyPSA.Statistics

- workflow/rules/retrieve.smk
- workflow/scripts/build_demand.py
- workflow/scripts/retrieve_eulp.py
In this PR I add logic to pull and process the [End-Use Load Profile](https://data.openei.org/submissions/4520) dataset from NREL. The data will come in at a state level, separated by electric, heating, and cooling load, and aggregated to an hourly load profile for 2018. I have not done the dissagregation yet, as we should decided on some common data structures for bringing in data. (ie. PR #202)
> And End Use Load Profile Demand 

- workflow/scripts/build_hydro_profile.py
- workflow/scripts/build_renewable_profiles.py
- workflow/scripts/cluster_network.py
Closes #263 
Fixes build warnings on duplicate label reference names. Module doc strings should now be displayed on the documentation site.
> Fix Docs Build Warnings

- README.md
- docs/requirements.txt
Closes #263
Add the following packages to the docs requirements file: 
- snakemake 
- cartopy 
- plotly
This should address the following warnings from readthedocs 
```bash 
WARNING: autodoc: failed to import module ...
```
> Fixes Docs Dependencies 

- workflow/rules/build_electricity.smk
- workflow/rules/retrieve.smk
- workflow/scripts/add_electricity.py
- workflow/scripts/build_base_network.py
- workflow/scripts/build_shapes.py
Closes #275 
In this PR I assign buses to counties in the base network. County level shapes have been added to the pypsa-usa databundle to zenodo. The county data is dropped at the end of add_electricity due to clustering issues if the shapes are retained. Counties are assigned their numerical value (geoid), rather than their human readable name. Note, counties are based on 2020 data, as this needs to be synced with population 2020 data.
> Adds county column to base network 

- docs/source/config-co2-base.md
- docs/source/config-configuration.md
- docs/source/config-sectors.md
- docs/source/config-wildcards.md
- docs/source/configtables/costs.csv
- docs/source/configtables/electricity.csv
- docs/source/configtables/sector.csv
- docs/source/index.md
- workflow/repo_data/config/config.default.yaml
- workflow/scripts/add_electricity.py
- workflow/scripts/prepare_network.py
Closes #220
Thanks for getting a bunch of this done, @ktehranchi! My updates are: 
- Updated the `sector` wildcards section 
- On the `retirement`, it was set up like it was a subdictionary under `electricity`. So I fixed that. 
- `Load` is removed in upcoming PR #288 and replaced by `scale`. 
- `OperationalReserves` added following PyPSA-Eur docs 
- Added demand config following updates from PR #202 
- Added `autarky` following PyPSA-Eur docs 
- Removed `co2_monthly_prices` as that pulled historical data for Europe model 
- Fixed sector config options
- Move interconnect co2 base values to its own unlisted page
> Docs updates

- .github/ISSUE_TEMPLATE/bug_report.yaml
- workflow/rules/retrieve.smk
- workflow/scripts/retrieve_pudl.py
Closes #311 
A new snakemake task that downloads the PUDL database.
> retrieve_pudl script

- workflow/Snakefile
- workflow/rules/build_electricity.smk
- workflow/scripts/add_demand.py
- workflow/scripts/add_electricity.py
- workflow/scripts/build_base_network.py
- workflow/scripts/build_demand.py
- workflow/scripts/cluster_network.py
- workflow/scripts/plot_statistics.py
- workflow/scripts/prepare_network.py
Closes #335 
In this PR I have changed the indexing logic to be the planning horizon instead of the profile year. This includes: 
- Adding multi-index to all snapshot data (regardless if it is single horizon or not) in `build_base_network`
- Updating demand to export planning horizon data (note, not scaled data yet) - the `expand_demand` function is a little awkward, but it will allow for addition of scaling demand relatively easily. 
- Updating data in `add_electricity` to account for planning horizon (ie. renewables, fuel prices, ect...) through updated `broadcast_investment_horizon_index` function 
I have checked that both single horizon and multi-horizon data still works. Todo before merging:
> Index snapshots by planning horizon 

- workflow/scripts/_helpers.py
- workflow/scripts/add_sectors.py
- workflow/scripts/build_base_network.py
- workflow/scripts/build_cutout.py
- workflow/scripts/build_demand.py
- workflow/scripts/build_fuel_prices.py
- workflow/scripts/build_renewable_profiles.py
- workflow/scripts/plot_validation_production.py
Closes #347, Closes #225 
Pulls in the PyPSA-Eur function for creating snapshots, which handles leap years (via the new function `get_snapshots(...)`). Current implementation is that leap year day (feb 29) will be dropped. Associated function calls throughout the workflow have been updated to always use this function. Creation of mulit-index snapshots has been updated to use this function and renamed to `get_multiindex_snapshots(...)`
> Fixes leap years

- workflow/repo_data/config/config.default.yaml
- workflow/repo_data/config/config.validation.yaml
- workflow/rules/common.smk
- workflow/scripts/add_electricity.py
- workflow/scripts/build_shapes.py
- workflow/scripts/plot_statistics.py
- workflow/scripts/solve_network.py
This change primarily updates unit-commitment parameters, ramping rates, and heat-rates for non-WECC generators.
- Generators with missing Unit-commitment parameters are assigned values from EIA-technology based capacity weighted averages from the ADS
- Likewise for the few plants missing e-grid heat-rates we update based on technology level capacity weighted averages.
- #16 Fix to ensure most of the renewable plants are added to the system. A small residual remains, need to investigate further why these aren't added to the network.
> Updates Unit Commitment Parameters

- workflow/Snakefile
- workflow/repo_data/config/config.default.yaml
- workflow/rules/build_electricity.smk
- workflow/scripts/build_demand.py
- workflow/scripts/plot_statistics.py
Closes #339 
Closes #276 
In this PR I add sacling to demand. Specifically;
- If EIA data is used, data is scaled according to AEO data (now pulled from PUDL). 
- If EFS data is used, data is interpolated between the two closes EFS years
- A Demand Formatter class is added which handles scaling and formatting data, regardless of sector. 
- The demand formatter will instantiate a DemandScaler object which handles logic for scaling specific data
While this is not the most efficient implementation (as, for example, EFS data has to get read in once during the reading/writing, and again for scaling), I beleive this is clearer and more maintainable for our current workload. But happy to discuss this point! :) 
This PR also removes the option of selecting scaling method in the configuration …
> Scales Demand 

- workflow/scripts/solve_network.py
Closes #413 
In this PR I have made the `multi_investment_period` option activated for solving, only when multi-period investment scenarios are run. This was causing a Linopy building error before.
> Fix for single period runs

- workflow/repo_data/config/config.sector.yaml
- workflow/scripts/build_heat.py
Closes #403 
In this PR I correct the service sector standing loss configuration option. Losses can be applied for both space and water heating; or just via space heating if space/water is not separated. Looses are applied as a per-unit per-hour loss. 
This is a little different than the PyPSA-Eur implementation. They input this as a time constant and calculate the loss via a decay function; may be worth looking into this in the future.
> Service sector standing losses

- workflow/repo_data/config/config.common.yaml
- workflow/repo_data/config/config.default.yaml
- workflow/repo_data/config/config.tutorial.yaml
- workflow/rules/build_electricity.smk
- workflow/scripts/add_electricity.py
- workflow/scripts/add_extra_components.py
- workflow/scripts/build_base_network.py
- workflow/scripts/cluster_network.py
- workflow/scripts/simplify_network.py
Within model_topology- user can now build networks that mesh multiple spatial scales.
```yaml
model_topology:
transmission_network: 'reeds' # [reeds, tamu]
topological_boundaries: 'reeds_zone' # [county, reeds_zone]
interface_transmission_limits: false
include: # mixed zone types not supported
reeds_state: ['CA']
aggregate: # eligible keys: [reeds_zone, trans_reg]
```
- Fixes bug with ReEDS Shapes where imprecise ReEDS GIS files leads to small number of ocean-side plants being dropped.
> Implements mixed resolution aggregations

- workflow/scripts/add_sectors.py
- workflow/scripts/build_stock_data.py
- workflow/scripts/solve_network.py
In this PR I implement a solution to get around the issue described in ticket #446. Moreover, CCS technologies have been corrected so they attach to the proper energy network (ie. CCGT-CCS is now a link in the gas network rather than a generator).
> Link to Generator fix 

- workflow/Snakefile
- workflow/scripts/add_electricity.py
- workflow/scripts/build_fuel_prices.py
- workflow/scripts/build_powerplants.py
- workflow/scripts/cluster_network.py
- Simplifies historical PUDL fuel cost imputations. Switches to using the fuel_cost_per_mmbtu to combine with the unit heat rates
- Increases the link capacities for a few links to match the configuration settings in ReEDS: (https://nrel.github.io/ReEDS-2.0/faq.html#is-there-a-way-to-reduce-solve-time)
- Adds a check in add_electricity to ensure plants are assigned to the correct State. This shouldn't impact many plants, but there were corner cases if plants were located right at the border of a State where they could be mis-assigned to their neighboring state.
> Minor Changes to historical fuel costs assignments, and matching reeds topology modifications

- workflow/repo_data/config/config.sector.yaml
- workflow/rules/build_sector.smk
- workflow/rules/retrieve.smk
- workflow/scripts/build_natural_gas.py
- workflow/scripts/plot_natural_gas.py
Closes #487,
Closes #438  
In this PR I add logic to correct pipeline capacity. As described in issue #487, the annual trade values do not necessarily respect design limits on pipeline capacity. This PR combines the two datasets to get the max capacity between the two. Also, the capacity dataset has been updated to 2024 data.
> Correct NG capacity 

- workflow/repo_data/config/config.default.yaml
- workflow/repo_data/config/config.plotting.yaml
- workflow/scripts/add_extra_components.py
- workflow/scripts/build_cost_data.py
- workflow/scripts/cluster_network.py
Implements new `hydrogen_ct` technology carrier using assumptions from ReEDS: https://nrel.github.io/ReEDS-2.0/model_documentation.html#hydrogen
- Assumes market purchase of zero carbon H2 which can be utilized in combustion turbine, uses default cost assumption from reeds ($20/MMbtu)
- New `min_year` configuration precludes build of hydrogen_ct to after 2040
> Implements h2-ct formulation

- docs/source/config-wildcards.md
- workflow/scripts/solve_network.py
Closes #520 
In this PR I update the TCT constraint logic. Specifically, I have removed existing capacity from the rhs of the constraint equation, and left the summation over only extendable generators. 
For example, if there is 10MW of existing solar capacity, and the target is at least 50MW, the constraint will read: 
```
sum(solar_ext_p_nom) >= 40
```
I think to improve interoperability between electricity and sector, it would be nice to not hard code in the `Generator` and `StorageUnit` component filtering, but I will add that as a new issue.
> Corrects TCT constraint 

- workflow/scripts/add_sectors.py
Closes #540
When converting generators to links, an `efficiecny2` was added to support state level co2 tracking. This introduced `nan` values for existing links. This PR addresses these warnings.
> Corrects `nan` in `efficiency2`

- workflow/repo_data/config/config.common.yaml
- workflow/rules/build_electricity.smk
- workflow/rules/retrieve.smk
- workflow/scripts/build_cost_data.py
- workflow/scripts/build_demand.py
- workflow/scripts/build_fuel_prices.py
- workflow/scripts/build_powerplants.py
- workflow/scripts/retrieve_pudl.py
Closes #564 , #469 
- Changes build_powerplants, build_fuel_prices, and build_cost_data to directly query the S3 hosted PUDL parquet files rather than downloading the entire pull.sqlite file from zenodo.
- Adds a new field in the `config.common.yaml` which tags the PUDL version to be used for all references to PUDL data.
- Removed hardcoded heat-rate/ static fuel cost data being pulled from 2019, now pulls from `renewable_weather_year` param. 
- [na] Changed dependencies are added to `envs/environment.yaml`.
- [na ] Changes in configuration options are also documented in `doc/configtables/*.csv`.
> Reference PUDL S3 Parquets instead of sqlite download, Lock PUDL version

- workflow/rules/build_electricity.smk
As PUDL is no longer tracked through snakemake (ie. its a cofig path), the input function for the demand scaling file failed as `config_provider("pudl_path")` is not a `str` or `list[str]`
Updated to return empty lists, as we hack in the file paths already (in the `*.py` file) for the demand scaling!
> Update PUDL path for sector studies

- docs/source/configtables/sector_natural_gas.csv
- docs/source/data-naturalgas.md
- workflow/repo_data/config/config.sector.yaml
- workflow/scripts/add_sectors.py
- workflow/scripts/build_emission_tracking.py
Closes #588 
This PR adds downstream emission leaks. Upstream leakage is applied at the `gas production` store. Downstream leakage applies to all links that originate at the state level gas tracking bus. All CH4 tracking has been moved the `bus3`/`efficiency3` attributes. CO2 tracking remains on the `bus2`/`efficiency2` attributes.
> Downstream Methane Leaks

- workflow/scripts/add_extra_components.py
- workflow/scripts/simplify_network.py
- Fixes implementation in PTC to properly account for discounting and tax credit monetization costs
- Patches small bug caused by pypsa where some clustered generators can end up with different build_years via floating point error in rounding. Need to investigate and reproduce to submit issue for pypsa.
> Fixes PTC Implementation

- workflow/rules/build_electricity.smk
- workflow/scripts/build_base_network.py
- workflow/scripts/constants.py
- workflow/scripts/opts/_helpers.py
- workflow/scripts/opts/policy.py
- workflow/scripts/solve_network.py
- Enables REC trading for RPS Opts according to Zones that roughly match the [epa attribute tracking regions](https://www.epa.gov/green-power-markets/energy-attribute-tracking-systems). All regions match with the exception of states split between PJM and MRETS. I will follow up with a PR that provides maps on each states eligible trading partners.
- Moves output of build_powerplants out of the RUN dependent resources subdirectory and into the base resources folder so that it doesn't get re-run between user runs. 
- Modifies TCT opt to use floating point precision rounding helper functions rather than the hackier plus epsilon
> Enable REC Trading for RPS Opt

- workflow/repo_data/config/config.common.yaml
- workflow/scripts/add_electricity.py
- workflow/scripts/build_fuel_prices.py
- workflow/scripts/build_powerplants.py
- workflow/scripts/simplify_network.py
- Bumps to PUDL version v2025.05.00
- Changes Query to now include plants under construction and retired plants. Previously when running historical simulations, we had not included recently retired power plants... this had a strong impact by tossing out recent coal retirements. 
- Minor refactor of build_powerplants to remove unused data and other small changes.
> PUDL Vers. Bump  v2025.05; Change to Query

- workflow/scripts/opts/sector.py
- workflow/scripts/solve_network.py
Closes #604
There seems to be an issue extracting dual values if we declare a dynamic/pnl GlobalConstraint. I'm not super sure why this isn't allowed by default, but this hotfix should correct it. This is tangentially related to [this issue](https://github.com/PyPSA/PyPSA/issues/850) on the main pypsa repo. 
In this hotfix, I just changed the co2 constraint to look at the last timeslice to ensure it meets limits, instead of every timestep. Therefore, it isnt caught up in the pnl io operations I guess. Alternatively, this code worked if we did not want to change the co2 constraint, however, its a little clunky. 
```
def _assign_duals_globalconstraint_fix(n: pypsa.Network):
"""
Assigns duals to global constraints.
This is a hacky fix where for a single pnl global constraint, names for duals …
```
> GlobalConstraint Dual Values Hotfix

- workflow/scripts/build_demand.py
Closes #618 
This PR updates the transport demand building to retain empty demand. This was originally added to speed up demand addition, by removing empty rows. The issue with that is if no demand exists (ie. 2030 efs reference case of heavy-duty electric vehicles), no demand nodes are built. Therefore, this solution takes the hit on efficiency (with retaining empty demand) but guarantees all buses are built.
> Retain empty demand

- docs/source/about-usage.md
- workflow/Snakefile
I had a request from a user to only generate the data model, without actually solving the network. This PR adds a `data_model` rule to do this. No logic is changed in this PR.
> Add `data_model` rule

- docs/source/configtables/sector_transport.csv
- docs/source/data-transportation.md
- workflow/repo_data/config/config.plotting.yaml
- workflow/repo_data/config/config.sector.yaml
- workflow/rules/build_electricity.smk
- workflow/rules/build_sector.smk
- workflow/scripts/add_demand.py
- workflow/scripts/add_sectors.py
- workflow/scripts/build_demand.py
- workflow/scripts/build_stock_data.py
- workflow/scripts/build_transportation.py
- workflow/scripts/constants_sector.py
- workflow/scripts/opts/sector.py
- workflow/scripts/plot_statistics_sector.py
- workflow/scripts/solve_network.py
Closes #625, #623, #618
In this PR I have made the following changes to the transport sector: 
- Ensured all EV loads from EFS have a profile. Before, if a vehicle mode was not used in EFS (ie. heavy duty trucks in 2030) the profile would be zero. In this case, I change it to a uniform load profile. 
- Removed exogenous road transportation investment from the model. Instead, all investment is endogenous and the user controls the allowable electrification per vehicle class per state per year. 
- Removed exogenous non-road investment from the model. This mimics the road transport, but everything still must be met by LPG right now. 
- Corrects the plotting issue, which had to do with existing links not being used, and instead being replaced with new links of the same technology. This turned …
> Endogenous Road Transport 

- docs/source/config-wildcards.md
- workflow/scripts/_helpers.py
- workflow/scripts/solve_network.py
Closes #626 
In this PR I have: 
- Made the `REM` `opts` wildcard useable for sector studies. The underlying logic hasnt changed, just that the user now has to specify `REM` to apply emission limits (akin to how to trigger limits for the power sector)
- Moved the addition of sector constraints to the main loop (rather than in a nested function) as variables in the global namespace are used in the constraint addition.
> `REM` for Sector Studies 

- workflow/scripts/build_natural_gas.py
- workflow/scripts/eia.py
Closes #650 
In this PR, I pull in citygate natural gas prices to apply to domestic imports/exports of natural gas from outside the model scope. This was applied to international imports/exports already. The logic has just been replicated for domestic connections.
> Domestic Natural Gas Import/Export Costs

- workflow/rules/build_electricity.smk
- workflow/scripts/build_base_network.py
Closes #662
Not a fix for #662, but just tells users that using the `model_topology.include` config options are not supported when `model_topology.topological_boundaries = "state"`. It directs users to the 662 ticket.
> Checks for correct topological settings when using state level boundaries
